// @ts-check
/**
 * Full-stack skill roadmap seed. Source section 25 is omitted — it only drives
 * default tiers. Job Readiness Criteria remains the final imported section.
 *
 * Per-item Medium overrides (even when the parent section is higher):
 *   WebSockets Basics, OpenAPI and Swagger Basics, Background Jobs Basics,
 *   Monitoring Basics, CI/CD Basics, Monitoring (Deployment and Production).
 */

/** @typedef {'Very High' | 'High' | 'Medium' | 'Secondary' | null} Tier */

/**
 * @typedef {{
 *   section: string,
 *   tier: Tier,
 *   groups: Array<{ subsection: string | null, items: string[] }>
 * }} RoadmapSection
 */

/** @type {RoadmapSection[]} */
export const ROADMAP = [
  {
    section: "1. Deep JavaScript",
    tier: "Very High",
    groups: [
      {
        subsection: "Language Fundamentals",
        items: [
          "let, const, var and temporal dead zone",
          "Primitive types vs. objects, and typeof pitfalls",
          "Numbers, IEEE-754, Number.isFinite, BigInt when you need it",
          "Strings, template literals, tagged templates",
          "Booleans and truthy/falsy without shooting yourself",
          "null vs. undefined vs. missing properties",
          "Equality: ===, Object.is, and when == still appears",
          "Type coercion rules you can actually remember",
          "Objects: literals, shorthand, computed keys, Object methods",
          "Property descriptors, freeze, seal, preventExtensions",
          "Arrays: map, filter, reduce, find, some, every, flat, flatMap",
          "Destructuring objects and arrays, rest and defaults",
          "Spread for clones vs. structuredClone vs. JSON roundtrip",
          "JSON.parse / stringify and reviver / replacer",
          "Sets, Maps, WeakMap, WeakSet and when they win",
          "Date, Temporal awareness, and timezone footguns",
          "Intl: NumberFormat, DateTimeFormat, Collator",
          "Regular expressions: test, exec, named groups, lastIndex",
          "Error types, throw, and Error.cause",
          "Optional chaining and nullish coalescing",
          "Logical assignment (||=, &&=, ??=)",
        ],
      },
      {
        subsection: "Functions and Scope",
        items: [
          "Function declarations vs. expressions vs. arrows",
          "this: default, implicit, explicit, new, and arrows",
          "call, apply, bind",
          "Closures as the reason hooks and callbacks work",
          "Lexical scope vs. dynamic scope (JS has the former)",
          "IIFE, modules, and why globals are a last resort",
          "Default parameters and arguments object",
          "Rest parameters vs. arguments",
          "Higher-order functions and function composition",
          "Pure functions vs. side effects",
          "Recursion and a stack-overflow instinct",
          "Generators and iterators, for...of, Symbol.iterator",
        ],
      },
      {
        subsection: "Asynchronous JavaScript",
        items: [
          "The event loop: call stack, microtasks, macrotasks",
          "Callbacks and callback hell as historical context",
          "Promises: then, catch, finally, chaining",
          "Promise.all, allSettled, race, any",
          "async/await and how it desugars to promises",
          "Error handling in async functions vs. floating promises",
          "AbortController and cancelling fetch",
          "queueMicrotask vs. setTimeout(0)",
          "requestAnimationFrame vs. setInterval for animation",
          "Debounce and throttle you could write from memory",
        ],
      },
      {
        subsection: "DOM and Browser APIs",
        items: [
          "Selecting: querySelector, querySelectorAll, closest",
          "Creating and inserting nodes without innerHTML XSS",
          "Events: capturing, bubbling, currentTarget vs. target",
          "addEventListener options: once, passive, signal",
          "Prevent default vs. stop propagation — and when neither",
          "Forms: FormData, constraint validation API",
          "Fetch API: method, headers, body, credentials, CORS mode",
          "URL, URLSearchParams, location, history",
          "localStorage, sessionStorage, and quota / privacy limits",
          "Cookies from JS vs. httpOnly (and why httpOnly exists)",
          "IntersectionObserver, ResizeObserver, MutationObserver",
          "Clipboard, notifications, and permission prompts",
          "Web Workers basics and when the main thread is drowning",
          "Modules in the browser: type=module, import maps",
        ],
      },
      {
        subsection: "Patterns and Quality",
        items: [
          "Modules: ESM vs. CJS, default vs. named exports",
          "Strict mode and why you already live in it",
          "Prototypes, prototype chain, and class sugar",
          "Getters, setters, and private fields (#)",
          "Static methods and static blocks",
          "Symbols and well-known symbols",
          "Proxy and Reflect (read, don't overuse)",
          "Memory leaks: detached DOM, forgotten listeners, closures",
          "console debugging that is better than console.log spaghetti",
          "WebSockets Basics",
        ],
      },
    ],
  },
  {
    section: "2. TypeScript",
    tier: "Very High",
    groups: [
      {
        subsection: "Types",
        items: [
          "Why TypeScript: types as a constraint, not a runtime",
          "tsc, tsconfig, target, module, moduleResolution, strict",
          "Primitive types, arrays, tuples, enums vs. union literals",
          "any vs. unknown vs. never vs. void",
          "Type aliases vs. interfaces",
          "Object types, optional properties, readonly, index signatures",
          "Union and intersection types",
          "Literal types and const assertions (as const)",
          "Narrowing: typeof, in, instanceof, equality, truthiness",
          "User-defined type guards (is) and asserts",
          "Discriminated unions as the everyday superpower",
          "Function types, overloads, this parameters",
          "Generics: functions, interfaces, classes, constraints",
          "Generic defaults and inference",
          "keyof, typeof, indexed access, mapped types",
          "Conditional types and infer",
          "Template literal types",
          "Utility types: Partial, Required, Pick, Omit, Record, Exclude, Extract, NonNullable, ReturnType, Parameters, Awaited",
          "typeof import() and module type queries",
        ],
      },
      {
        subsection: "Working with Real Code",
        items: [
          "tsconfig strict family: strictNullChecks, noImplicitAny, etc.",
          "noUncheckedIndexedAccess and why it hurts then helps",
          "Declaration files (.d.ts) and @types packages",
          "Module augmentation and declare module",
          "JSX types: ReactNode, ComponentProps, CSSProperties",
          "Typing fetch responses without lying to yourself",
          "Zod (or similar) for runtime validation at boundaries",
          "satisfies operator vs. annotation vs. assertion",
          "as casts: last resort, never the first",
          "Path aliases and how they break at runtime if unbundled",
          "Project references and composite for large repos",
          "Isolated modules and why bundlers require them",
          "SkipLibCheck and when it hides real problems",
          "ESLint typescript-eslint recommended + stylistic split",
          "Pretty-ts-errors / ts-error translator as a learning tool",
          "Migrating a JS file with checkJs / allowJs",
        ],
      },
    ],
  },
  {
    section: "3. HTML and CSS",
    tier: null,
    groups: [
      {
        subsection: "HTML",
        items: [
          "HTML document outline: doctype, html, head, body",
          "Semantic landmarks: header, nav, main, article, aside, footer",
          "Headings h1–h6 as a real outline, not for size",
          "Paragraphs, lists, blockquote, pre, code, hr",
          "Links: href, download, mailto, target and when not to use it",
          "Images: src, alt, width/height, srcset and sizes",
          "Picture element and art direction",
          "Audio and video elements, captions track",
          "Tables: caption, thead, tbody, th scope, col",
          "Forms: form, fieldset, legend, label for/id pairing",
          "Input types: text, email, url, number, date, file, checkbox, radio, hidden",
          "Select, textarea, datalist, output, progress, meter",
          "Button types: submit, reset, button — and default type gotchas",
          "Required, disabled, readonly, minlength, pattern, autocomplete",
          "Details/summary, dialog, and native popover",
          "Iframe basics, sandbox, and why title matters",
          "Meta tags: charset, viewport, description, robots",
          "Favicon, apple-touch-icon, and theme-color",
          "Language and dir attributes",
          "Custom data attributes vs. proper attributes",
          "HTML validation (W3C) and common parser quirks",
        ],
      },
      {
        subsection: "CSS",
        items: [
          "The cascade, origin, importance, and layer (@layer)",
          "Specificity: inline, id, class, type, :where vs :is",
          "Inheritance and the inherit / initial / unset / revert keywords",
          "Box model: content, padding, border, margin, box-sizing",
          "Display: block, inline, inline-block, none, contents",
          "Flow layout, formatting contexts, and margin collapse",
          "Position: static, relative, absolute, fixed, sticky",
          "Z-index, stacking contexts, and isolation",
          "Overflow, scroll snapping, and scrollbar styling",
          "Units: px, rem, em, %, vh/vw, dvh, ch, lh, svh",
          "Colors: hex, rgb, hsl, oklch, currentColor, color-mix",
          "Custom properties (CSS variables) and fallbacks",
          "Typography: font-family, font-face, font-display, line-height, letter-spacing",
          "System font stacks vs. variable fonts vs. Google Fonts",
          "Text wrapping: overflow-wrap, line-break, text-wrap balance/pretty",
          "Lists, counters, and generated content",
          "Backgrounds, gradients (quietly), and background-size",
          "Borders, outline vs. border, border-image (when to skip)",
          "Border-radius and concentric inner radii",
          "Box-shadow and text-shadow — hairlines, not glow soup",
          "Transforms: translate, scale, rotate, transform-origin",
          "Transitions on specific properties only (never all)",
          "Keyframe animations reserved for one-shot sequences",
          "prefers-reduced-motion and prefers-color-scheme",
          "Cursor, user-select, pointer-events, touch-action",
        ],
      },
      {
        subsection: "Layout",
        items: [
          "Flexbox: axis, wrap, justify, align, gap, flex shorthand",
          "Flex: shrinking, growing, and min-width: auto gotchas",
          "CSS Grid: tracks, areas, auto-fit/auto-fill, minmax, subgrid",
          "Grid vs. flex: pick one per layout problem",
          "Multicolumn layout and when not to use it",
          "Container queries and container query units",
          "Media queries: width, hover, pointer, resolution",
          "Mobile-first breakpoints and content-driven widths",
          "Logical properties: inset, margin-inline, padding-block",
          "Aspect-ratio and object-fit for media",
          "Sticky headers and scroll-padding for in-page anchors",
          "Holy-grail / sidebar + main layouts without hacks",
        ],
      },
      {
        subsection: "Responsive and Polish",
        items: [
          "Responsive images that do not layout-shift",
          "Fluid type with clamp()",
          "Spacing scale (4/8) instead of magic numbers",
          "Dark mode with custom properties, not a second stylesheet",
          "Print styles: hide chrome, show URLs, page-break",
          "Focus-visible rings that meet contrast",
          "Hit targets ≥ 44px on touch (padding, not just icon size)",
          "Horizontal overflow hunting on 390px viewports",
        ],
      },
    ],
  },
  {
    section: "4. React",
    tier: "Very High",
    groups: [
      {
        subsection: "Core",
        items: [
          "What React is (and is not): UI = f(state)",
          "JSX, fragments, and expressions in markup",
          "Elements vs. components vs. instances",
          "Function components and props as a contract",
          "Children, composition over inheritance",
          "Key prop: identity across reconciliations",
          "Lists: map, stable ids, never index if the list mutates",
          "Conditional rendering without && 0 traps",
          "Controlled vs. uncontrolled inputs",
          "Events: synthetic events, naming, preventDefault",
          "Forms in React: state, FormData, action functions",
          "Refs: DOM refs, callback refs, forwardRef / useImperativeHandle",
          "Portals for modals and toasts",
          "Error boundaries (class, and the future of function ones)",
        ],
      },
      {
        subsection: "Hooks",
        items: [
          "Rules of Hooks — no conditionals, no loops",
          "useState: functional updates, lazy init, batching",
          "useReducer for related state transitions",
          "useEffect: sync with the outside world, not for derived state",
          "Effect dependencies and stale closures",
          "Cleanup functions: subscriptions, timers, abort",
          "useLayoutEffect — measure, then paint; rarely",
          "useMemo vs. useCallback: measure before you sprinkle",
          "useRef for mutable boxes that don't re-render",
          "useId for SSR-safe ids",
          "useContext and when context is the wrong tool",
          "useSyncExternalStore for external stores",
          "useDeferredValue and useTransition for non-urgent UI",
          "useOptimistic for instant local updates",
          "Custom hooks: name, return shape, one job",
        ],
      },
      {
        subsection: "Data and Architecture",
        items: [
          "Lifting state vs. colocating state",
          "Derived state: compute, don't store",
          "Prop drilling and the three ways out (compose, context, store)",
          "Server vs. client components (conceptual, even before Next)",
          "Data fetching: where it lives, waterfalls, caching",
          "TanStack Query: queries, mutations, invalidation, optimistic updates",
          "Zustand or equivalent for client UI state that isn't server data",
          "URL as state: search params, filters, pagination",
          "Code splitting: lazy, Suspense, route-level splits",
          "Suspense for data (mental model)",
        ],
      },
      {
        subsection: "Patterns and Pitfalls",
        items: [
          "Don't put hooks after a conditional return",
          "Don't derive state in an effect",
          "Don't copy props into state unless you mean 'initial'",
          "Don't mutate arrays/objects — replace them",
          "Avoid index as key for inserts/deletes/sorts",
          "Avoid giant providers that re-render the world",
          "Compound components and context for flexible APIs",
          "Headless UI / Radix primitives vs. rolling your own dialog",
          "Accessibility in custom widgets (focus trap, aria, keyboard)",
          "Testing components: user-centric queries, not implementation",
        ],
      },
    ],
  },
  {
    section: "5. Next.js",
    tier: "Very High",
    groups: [
      {
        subsection: "App Router",
        items: [
          "App Router file conventions: page, layout, loading, error, not-found",
          "Nested layouts and templates",
          "Route groups and parallel routes (know; use sparingly)",
          "Dynamic segments, catch-all, optional catch-all",
          "Route handlers (app/api) vs. server actions vs. server functions",
          "Metadata API: title, description, open graph (framework side)",
          "generateStaticParams and dynamicParams",
          "route.ts special files: sitemap, robots, manifest",
        ],
      },
      {
        subsection: "Rendering and Data",
        items: [
          "Server Components vs. Client Components — the 'use client' boundary",
          "Passing serializable props across the boundary",
          "fetch on the server: cache, revalidate, no-store",
          "Request memoization and the fetch cache",
          "Streaming and Suspense boundaries",
          "Partial prerendering mental model",
          "Static vs. dynamic rendering, and what forces dynamic",
          "Cookies, headers, and draft mode as dynamic signals",
          "Server Actions: form actions, progressive enhancement",
          "revalidatePath / revalidateTag",
          "Image component: sizes, priority, remote patterns",
          "Font optimization and next/font",
          "Script strategy: beforeInteractive, afterInteractive, lazyOnload",
        ],
      },
      {
        subsection: "Production Habits",
        items: [
          "Environment variables: NEXT_PUBLIC_ vs. server-only",
          "Redirects and rewrites in next.config",
          "Middleware: auth gates, geo, A/B — keep it tiny",
          "Edge vs. Node runtimes and what you cannot import",
          "Bundle analyzer and 'why is this in the client graph?'",
          "Error.tsx vs. global-error vs. instrumentation",
          "Vercel / Node hosting differences (filesystem, cron, limits)",
        ],
      },
    ],
  },
  {
    section: "2. Backend and Node.js",
    tier: "Very High",
    groups: [
      {
        subsection: "Node Runtime",
        items: [
          "What Node is: V8 + libuv + modules",
          "The event loop in Node (timers, I/O, check, close)",
          "process, env, argv, cwd, exit codes",
          "ESM vs. CJS in Node, 'type': 'module', createRequire",
          "Builtins: fs, path, url, crypto, stream, buffer, http",
          "Promises in fs vs. callbacks vs. sync — prefer promises",
          "Streams: readable, writable, pipeline, backpressure",
          "Buffer vs. string vs. Uint8Array",
          "crypto: hashing, hmac, randomBytes, timingSafeEqual",
          "child_process and when not to shell out",
          "Error-first callbacks as archaeology; use promises",
          "Unhandled rejections and crash-on-bug in production",
          "node:test or Vitest for unit tests of pure modules",
        ],
      },
      {
        subsection: "HTTP Servers",
        items: [
          "http.createServer as the floor, a framework as the house",
          "Express / Fastify / Hono: routing, middleware, plugins",
          "Request lifecycle: parse, auth, validate, handle, respond",
          "Middleware order and why it bites",
          "Body parsing: json, urlencoded, multipart — size limits",
          "Static files: when the app shouldn't serve them",
          "Graceful shutdown: drain connections, stop taking work",
          "Health endpoints: /healthz live vs. ready",
          "Config via env, not magic files committed with secrets",
          "Structured logging (pino / winston) with request ids",
          "Background Jobs Basics",
        ],
      },
      {
        subsection: "Architecture",
        items: [
          "Layering: route → service → data, keep HTTP out of the core",
          "One process vs. workers vs. a queue",
          "Stateless app servers: session in DB/cookie, not memory",
          "Idempotent handlers for retries and double-clicks",
          "Outbound HTTP: timeouts, retries, circuit breakers (simple)",
          "File uploads to object storage, not the app disk",
          "Email, SMS, payments: treat as unreliable integrations",
          "Feature flags vs. env flags vs. just shipping the code",
          "12-factor: disposability, config, backing services",
        ],
      },
    ],
  },
  {
    section: "7. REST APIs and HTTP",
    tier: "Very High",
    groups: [
      {
        subsection: "HTTP",
        items: [
          "URL anatomy: scheme, host, path, query, fragment",
          "DNS, TCP, TLS, HTTP — the request journey",
          "HTTP/1.1 vs. HTTP/2 vs. HTTP/3 at a practical level",
          "Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS",
          "Idempotency and safety of methods",
          "Status codes: 2xx, 3xx, 4xx, 5xx you will actually use",
          "Headers: Content-Type, Accept, Authorization, Cache-Control, ETag, Cookie",
          "CORS: simple vs. preflight, credentials, allowed origins",
          "Redirects: 301/302/307/308 and method preservation",
          "Content negotiation and charset",
          "Cookies: Expires, Max-Age, Domain, Path, Secure, HttpOnly, SameSite",
          "Compression: gzip, br, and why you don't gzip twice",
        ],
      },
      {
        subsection: "REST Design",
        items: [
          "Resources as nouns, not verbs, in URLs",
          "Plural collections: /items, /items/:id",
          "Query params for filter, sort, pagination — not a second RPC",
          "Request and response JSON shapes that stay boring",
          "Pagination: offset vs. cursor, total counts, Link headers",
          "Filtering, sorting, sparse fieldsets",
          "Versioning: URL vs. header vs. don't until you must",
          "Error body: machine code + human message + field errors",
          "Idempotency keys for payments and POSTs that retry",
          "HATEOAS awareness (know it; don't overbuild it)",
          "Webhooks vs. polling vs. SSE vs. WebSockets — pick per job",
          "Rate limiting headers and 429 with Retry-After",
          "OpenAPI and Swagger Basics",
          "Postman / Insomnia / httpie / curl as daily tools",
          "Contract tests against the OpenAPI spec",
        ],
      },
    ],
  },
  {
    section: "8. PostgreSQL",
    tier: "Very High",
    groups: [
      {
        subsection: "Relational Model",
        items: [
          "Tables, rows, columns, types that match the domain",
          "Primary keys: identity/serial vs. uuid vs. text",
          "Foreign keys and ON DELETE/UPDATE actions",
          "NOT NULL, UNIQUE, CHECK, DEFAULT",
          "Normalization (1NF–3NF) and when to denormalize on purpose",
          "One-to-one, one-to-many, many-to-many (join tables)",
          "Surrogate vs. natural keys",
        ],
      },
      {
        subsection: "SQL",
        items: [
          "SELECT, FROM, WHERE, ORDER BY, LIMIT, OFFSET",
          "JOINs: inner, left, right, full, cross — and when each",
          "GROUP BY, HAVING, aggregates (count, sum, avg, min, max)",
          "NULL three-valued logic and IS DISTINCT FROM",
          "Subqueries, CTEs (WITH), and when a join is clearer",
          "UNION / INTERSECT / EXCEPT",
          "Window functions: row_number, rank, lag, lead, partitions",
          "INSERT, UPDATE, DELETE, RETURNING",
          "UPSERT: ON CONFLICT DO UPDATE / DO NOTHING",
          "Transactions: BEGIN, COMMIT, ROLLBACK",
          "Isolation levels and what you actually need (read committed)",
          "SELECT FOR UPDATE when two requests race",
          "Prepared statements and parameter binding ($1) — never string concat",
          "EXPLAIN and EXPLAIN ANALYZE as a habit",
        ],
      },
      {
        subsection: "Postgres Specifics",
        items: [
          "Types: text, int, bigint, numeric, boolean, timestamptz, date, jsonb, uuid, arrays",
          "timestamptz vs. timestamp — always timestamptz",
          "jsonb operators, containment, GIN indexes",
          "Indexes: btree default, what they speed up, what they cost",
          "Composite and partial indexes",
          "Unique indexes vs. unique constraints",
          "Migrations as the only schema source",
          "Connection pooling (PgBouncer / pooler) vs. too many clients",
          "VACUUM, bloat, and why deletes are not free",
          "Extensions awareness (pgcrypto, pg_trgm) — only if the host has them",
          "Backup and restore: pg_dump, point-in-time on a host",
        ],
      },
    ],
  },
  {
    section: "9. Prisma",
    tier: "Very High",
    groups: [
      {
        subsection: "Schema and Migrate",
        items: [
          "schema.prisma: generators, datasource, models",
          "Scalar types and @id, @unique, @default, @map, @@map",
          "Relations: one-to-many, many-to-many, referential actions",
          "Enums in Prisma vs. enums in Postgres",
          "prisma migrate dev vs. deploy vs. db push (and when push is a trap)",
          "Migration files as reviewed artifacts",
          "Seeding with prisma db seed",
          "Introspection vs. schema-first — pick one",
          "Preview features: read the release notes before flipping",
        ],
      },
      {
        subsection: "Client",
        items: [
          "PrismaClient singleton (don't new it per request in serverless)",
          "CRUD: findMany, findUnique, create, update, delete, upsert, count",
          "where, orderBy, take, skip, cursor pagination",
          "select vs. include vs. omit — don't over-fetch",
          "Nested writes and nested reads",
          "Transactions: $transaction sequential vs. interactive",
          "Middleware / extensions / client extensions",
          "Raw SQL: $queryRaw tagged template vs. $executeRaw — still parameterized",
          "Error codes: P2002 unique, P2025 not found, P2003 FK",
          "Typing: generated client as the source of types",
          "Prisma in tests: test DB, or transaction rollback, not production",
          "N+1: include, or a second query, never a loop of findUnique",
          "Soft delete vs. hard delete — schema it on purpose",
          "Prisma vs. Kysely vs. Drizzle: you can read the others",
        ],
      },
    ],
  },
  {
    section: "3. Authentication and Authorization",
    tier: "Very High",
    groups: [
      {
        subsection: "Authentication",
        items: [
          "Authentication (who) vs. authorization (what)",
          "Session cookies vs. JWTs vs. opaque tokens — tradeoffs",
          "Password hashing: argon2/scrypt/bcrypt, never md5/sha, never reversible",
          "Salts, peppers, and timing-safe compare",
          "Email verification and password reset as tokenized one-time links",
          "MFA TOTP basics",
          "OAuth 2.0 roles: resource owner, client, auth server, resource server",
          "Authorization code + PKCE for browser apps",
          "OpenID Connect: id token vs. access token",
          "Social login: you still need an app-side user row",
          "CSRF on cookie sessions: SameSite and/or double-submit / synchronizer",
          "Secure cookie flags: HttpOnly, Secure, SameSite",
          "Session rotation on login and privilege change",
          "Logout: server-side revoke, not just delete a cookie",
          "Rate-limit login and reset endpoints",
        ],
      },
      {
        subsection: "Authorization",
        items: [
          "Never trust a client-sent user id",
          "Scope every query by the verified user (or role)",
          "RBAC: roles as coarse gates",
          "Resource ownership checks on every mutation",
          "IDOR: changing /items/42 to /items/43",
          "Principle of least privilege for API keys and DB roles",
          "Service-role keys never shipped to the browser",
          "Public vs. authenticated vs. admin routes",
          "Audit log for sensitive actions",
        ],
      },
    ],
  },
  {
    section: "11. Web Security",
    tier: "High",
    groups: [
      {
        subsection: "OWASP Top Class",
        items: [
          "XSS: HTML injection, attribute, JS context — encode/escape per context",
          "CSP as defense in depth, not the only door",
          "CSRF: cookies and state-changing requests",
          "SQL injection: parameterized queries only, always",
          "Command injection: never interpolate into a shell",
          "Path traversal and file download endpoints",
          "SSRF: don't fetch user URLs without an allowlist",
          "Open redirects",
          "Clickjacking: X-Frame-Options / frame-ancestors",
          "Insecure deserialization",
          "Using components with known vulnerabilities (audit, dependabot)",
          "Broken access control (the #1 real-world bug)",
        ],
      },
      {
        subsection: "Hardening",
        items: [
          "HTTPS only, Secure cookies, HSTS",
          "Security headers: CSP, Referrer-Policy, Permissions-Policy, X-Content-Type-Options",
          "CORS least privilege, never * with credentials",
          "Rate limiting and lockout on auth",
          "Secrets: env, not git; rotate when leaked",
          "Principle of least privilege on cloud keys",
          "Dependency pinning and npm audit in CI (with judgment)",
          "File upload: store outside web root / in object storage, random names, scan size/type",
          "Don't roll your own crypto",
          "Threat model a feature in one paragraph before you build it",
        ],
      },
    ],
  },
  {
    section: "4. Validation and Error Handling",
    tier: "Very High",
    groups: [
      {
        subsection: "Validation",
        items: [
          "Validate at the boundary: user input, query params, env, webhooks",
          "Never trust the client: server re-validates always",
          "Schema-first with Zod (or Yup/Valibot) shared where it is safe",
          "Required vs. optional vs. nullable — three different things",
          "String limits, trimming, empty-string vs. missing",
          "Numbers: int vs. float, min/max, NaN",
          "Enums and literal unions instead of free-text statuses",
          "Emails, URLs, UUIDs: use the library, not a cute regex",
          "Dates: ISO-8601, timezones, and 'is this in the future?'",
          "Nested objects and arrays: min length, unique items",
          "Cross-field rules (password confirm, start < end)",
          "File uploads: type, size, and don't trust the extension",
          "Normalize then validate (lowercase email, trim)",
          "Return field-level errors the UI can place",
        ],
      },
      {
        subsection: "Error Handling",
        items: [
          "Expected vs. unexpected errors (domain vs. bugs)",
          "HTTP mapping: 400 validation, 401 auth, 403 forbidden, 404, 409 conflict, 429, 500",
          "Don't leak stack traces to clients",
          "Central error middleware / handler on the server",
          "Error.cause and wrapping without losing the original",
          "Result types vs. throw — pick a house style and keep it",
          "Retries: only idempotent, with backoff and jitter",
          "Timeouts on every outbound call",
          "User-facing copy: what happened, what to do next",
          "Logging errors with request id / correlation id",
          "Crash vs. isolate: unhandledRejection, render error boundaries",
        ],
      },
    ],
  },
  {
    section: "13. Testing",
    tier: "High",
    groups: [
      {
        subsection: "Mindset",
        items: [
          "The test pyramid without religion: unit, integration, e2e",
          "Test behavior users care about, not implementation trivia",
          "Arrange, act, assert",
          "Determinism: no real time, network, or randomness unless injected",
          "A failing test must mean a real problem (kill flakes)",
          "Coverage as a spotlight, not a score",
        ],
      },
      {
        subsection: "Unit and Integration",
        items: [
          "Vitest / Jest / node:test — pick one and know watch, coverage, ui",
          "Assertions that read like English",
          "Mocks vs. fakes vs. stubs — and over-mocking as a smell",
          "Testing pure functions is free; start there",
          "Testing Zod schemas and error mapping",
          "Testing SQL against a real Postgres (or PGLite) when the query is the point",
          "Factory helpers for test data, not a 200-line beforeEach",
          "Testing React: Testing Library, user-event, role queries",
          "Don't test that a className exists; test the name/role/text",
        ],
      },
      {
        subsection: "E2E and CI",
        items: [
          "Playwright: locators, web-first assertions, trace viewer",
          "Page objects only when they reduce duplication, not as ceremony",
          "Seed a known DB state for e2e; never depend on last run",
          "Visual regression: screenshot compare for the few screens that matter",
          "Run unit tests on every PR; e2e on main / nightly if slow",
          "CI must be the same commands you run locally",
          "Quarantine vs. fix: a skipped flake is still a bug",
        ],
      },
    ],
  },
  {
    section: "14. Git and GitHub",
    tier: "High",
    groups: [
      {
        subsection: "Git",
        items: [
          "Mental model: commits, trees, blobs, refs",
          "status, diff, log, show",
          "add, commit, amend (only if not pushed)",
          "branch, switch/checkout, merge, rebase",
          "When to rebase vs. merge",
          "stash, including -u",
          "reset --soft/--mixed/--hard and the reflog as a safety net",
          "revert as the safe undo for public history",
          "cherry-pick",
          "tags (annotated) for releases",
          "gitignore, and not using it as a broom for secrets",
          "hooks: pre-commit for lint/format (husky / leftover / lefthook)",
          "Worktrees for parallel branches",
          "bisect for 'when did this break?'",
        ],
      },
      {
        subsection: "GitHub",
        items: [
          "Clone, fork, remote, fetch, pull, push",
          "SSH keys vs. HTTPS + credential helper",
          "PRs: small, described, screenshot if UI",
          "Reviewing: request changes vs. comment vs. approve",
          "CODEOWNERS, branch protection, required checks",
          "Issues, labels, milestones — enough to be a teammate",
          "GitHub Actions as a consumer (see also CI/CD)",
          "Dependabot / renovate at a glance",
          "Never force-push main; never commit .env",
          "Conventional commits or a house style — pick and keep",
        ],
      },
    ],
  },
  {
    section: "15. Docker",
    tier: "High",
    groups: [
      {
        subsection: "Images and Containers",
        items: [
          "Image vs. container vs. volume vs. network",
          "Dockerfile: FROM, WORKDIR, COPY, RUN, ENV, EXPOSE, CMD vs. ENTRYPOINT",
          "Layer caching: order instructions so deps don't bust on every copy",
          "Multi-stage builds for small Node images",
          ".dockerignore (node_modules, .git, .env)",
          "Don't run as root in the container",
          "Pin base image tags; avoid :latest in production",
          "Healthcheck instruction vs. orchestrator probes",
          "docker build, run, ps, logs, exec, stop, rm, images, prune",
          "Bind mounts vs. named volumes",
          "docker compose: services, env, depends_on, healthchecks",
          "Compose for local Postgres + app + migrate",
          "Inspecting: docker inspect, stats, port",
          "Registries: Docker Hub, ghcr, pulling and pushing",
          "Security: scan images, drop capabilities, read-only FS where possible",
        ],
      },
    ],
  },
  {
    section: "5. Linux and VPS",
    tier: "High",
    groups: [
      {
        subsection: "Linux",
        items: [
          "Filesystem: /, /etc, /var, /home, /tmp, /usr",
          "ls, cd, pwd, tree, find, locate",
          "cat, less, head, tail -f, wc, sort, uniq",
          "grep, ripgrep, sed, awk at a reading level",
          "Permissions: rwx, chmod, chown, umask, sticky bit instinct",
          "Users, groups, sudo, visudo",
          "Processes: ps, top/htop, kill, nice, jobs, nohup, systemd",
          "systemd units: start, stop, enable, status, journalctl",
          "Networking: ip, ss, curl, wget, dig, traceroute",
          "ssh, ssh-keygen, authorized_keys, config Host blocks",
          "scp / rsync",
          "disk: df, du, lsblk, mount",
          "env, exports, PATH, dotfiles (.bashrc)",
          "cron / systemd timers",
        ],
      },
      {
        subsection: "VPS",
        items: [
          "Picking a VPS: CPU, RAM, disk, region, backups",
          "Initial harden: updates, new user, disable root SSH password",
          "UFW / nftables: deny by default, allow 22/80/443",
          "fail2ban or equivalent for SSH",
          "Nginx or Caddy as reverse proxy + TLS",
          "Let's Encrypt / Caddy automatic certs",
          "Process manager: systemd for Node, or a container runtime",
          "Swap, OOM, and why 512MB boxes die",
          "Monitoring Basics",
          "Offsite backups you have actually restored once",
        ],
      },
    ],
  },
  {
    section: "17. Deployment and Production",
    tier: "High",
    groups: [
      {
        subsection: "Shipping",
        items: [
          "Environments: local, preview, production — same artifact if you can",
          "Build vs. runtime env vars",
          "Zero-downtime: draining, rolling, blue/green at a conceptual level",
          "Migrations in deploy: expand/contract, never break old code + new schema",
          "Health checks that fail when the DB is gone",
          "Logs: stdout, structured JSON, one request id",
          "Error tracking (Sentry or similar) with release versions",
          "Uptime checks from outside the box",
          "Domains, DNS A/AAAA/CNAME, TTL",
          "TLS everywhere, HSTS once you're sure",
          "Preview deploys on PRs",
          "Rollback plan that is a button, not a prayer",
        ],
      },
      {
        subsection: "CI/CD and Ops",
        items: [
          "CI/CD Basics",
          "GitHub Actions: workflows, jobs, steps, secrets, caching",
          "Run lint, typecheck, unit tests, then build",
          "Deploy on main (or on tag) after green checks",
          "Pin action versions by SHA when it matters",
          "Monitoring",
          "Metrics: latency, error rate, saturation (the golden signals)",
          "Alert on symptoms users feel, not disk 70% on Tuesday",
        ],
      },
    ],
  },
  {
    section: "18. Performance and Scalability",
    tier: "High",
    groups: [
      {
        subsection: "Frontend Performance",
        items: [
          "Core Web Vitals: LCP, INP, CLS — what they measure",
          "Network: fewer bytes, fewer requests, HTTP cache",
          "Images: right format, right size, lazy vs. priority",
          "Fonts: subset, font-display, avoid FOIT",
          "JS budget: code split, tree shake, don't ship the kitchen",
          "CSS: avoid giant unused frameworks on a 4-page site",
          "Critical rendering path, preload, preconnect (sparingly)",
          "Hydration cost and islands / server components as a response",
          "Lists: virtualize when you actually have thousands of rows",
          "Debounce input-driven fetches",
        ],
      },
      {
        subsection: "Backend and Data",
        items: [
          "Measure before you scale: a timer around the slow thing",
          "Indexes for the queries you run, not the ones you imagine",
          "N+1 queries as the default backend footgun",
          "Pagination so you never SELECT * FROM big_table",
          "Caching: in-process, Redis, HTTP — invalidation is the work",
          "Cache-Control, ETag, stale-while-revalidate",
          "Connection pool size vs. Postgres max_connections",
          "Background work off the request thread",
          "Horizontal scale requires stateless app servers",
          "Read replicas conceptually; don't jump there first",
          "Load testing with a realistic mix, not 10k GET /",
        ],
      },
    ],
  },
  {
    section: "6. UI, UX, and Accessibility",
    tier: "High",
    groups: [
      {
        subsection: "UX",
        items: [
          "Visual hierarchy: one primary action per view",
          "Fitts's law: make frequent targets big and close",
          "Hick's law: fewer choices, clearer defaults",
          "Empty, loading, and error states as first-class design",
          "Optimistic UI vs. waiting vs. skeletons — pick on purpose",
          "Undo is better than a confirm dialog for reversible acts",
          "Toast vs. inline error vs. page-level alert",
          "Forms: labels, help text, errors next to fields",
          "Progressive disclosure: hide advanced until needed",
          "Mobile-first: thumbs, not hover",
          "Don't block paste on password fields",
          "Copy that uses verbs and names the object",
        ],
      },
      {
        subsection: "Accessibility",
        items: [
          "WCAG 2.2 AA as the bar, not a stretch goal",
          "Semantic HTML is 80% of a11y",
          "Keyboard: tab order, skip link, no keyboard traps",
          "Focus visible always; don't outline: none without a replacement",
          "ARIA roles, states, properties — only when HTML is not enough",
          "Accessible names: label, aria-label, aria-labelledby",
          "Live regions for async updates (polite vs. assertive)",
          "Images: meaningful alt, decorative alt='', never missing",
          "Color contrast (text and UI components)",
          "Don't convey meaning by color alone",
          "Motion: respect prefers-reduced-motion",
          "Form errors announced and associated with fields",
          "Modals: focus trap, return focus, Escape to close, aria-modal",
          "Screen reader testing: VoiceOver or NVDA once per feature",
          "axe / eslint-plugin-jsx-a11y in CI",
        ],
      },
    ],
  },
  {
    section: "20. Supporting Tools",
    tier: null,
    groups: [
      {
        subsection: "Editor",
        items: [
          "VS Code (or equivalent) as daily driver",
          "Command palette, multi-cursor, and jump-to-definition",
          "Format on save with a project formatter",
          "EditorConfig so tabs/newlines match the repo",
          "Emmet for HTML/CSS, then knowing when to stop",
          "Snippets for the few patterns you actually type",
          "Integrated terminal and tasks",
          "Extensions: ESLint, Prettier, Tailwind IntelliSense, Prisma, Pretty TS Errors",
          "Disable noisy extensions; keep the editor fast",
        ],
      },
      {
        subsection: "Browser DevTools",
        items: [
          "Elements panel: inspect, force state, edit HTML/CSS live",
          "Computed styles vs. authored styles",
          "Box model overlay and grid/flex inspector",
          "Console: log, table, assert, copy, $0",
          "Network: waterfall, headers, preview, disable cache, throttling",
          "Application: cookies, local/session storage, cache storage",
          "Sources: breakpoints, conditional breakpoints, blackboxing",
          "Performance panel: record, FPS, long tasks",
          "Lighthouse and what each category actually means",
          "Accessibility tree and contrast checker",
          "Responsive design mode and device emulation caveats",
        ],
      },
      {
        subsection: "Package Managers and CLI",
        items: [
          "npm vs. pnpm vs. yarn — lockfiles and why they matter",
          "package.json scripts, engines, and sideEffects",
          "npx / pnpx for one-off tools",
          "Semver: caret, tilde, exact, and peer dependencies",
          "Updating deps without surprise major bumps",
          "Reading a README and changelog before adding a library",
          "Why not to commit node_modules",
        ],
      },
    ],
  },
  {
    section: "21. Golang",
    tier: "Secondary",
    groups: [
      {
        subsection: "Language",
        items: [
          "Why Go shows up in backend job specs",
          "go run, go build, go test, go mod",
          "Packages, modules, internal/, exported names (Capitals)",
          "Types, structs, pointers, slices, maps",
          "Zero values and making them useful",
          "Interfaces: small, implicit, io.Reader instinct",
          "Errors as values: error, fmt.Errorf, errors.Is/As",
          "defer, panic, recover (recover is for boundaries)",
          "Goroutines and channels at a reading level",
          "context.Context for cancel and deadlines",
          "A table-driven test",
          "gofmt / goimports as non-negotiable",
        ],
      },
      {
        subsection: "Web in Go",
        items: [
          "net/http handlers and ServeMux",
          "Middleware as wrapping Handler",
          "encoding/json and struct tags",
          "sql + database/sql or a small wrapper; migrations still exist",
          "A tiny REST service you could write in a weekend",
          "When to pick Go over Node (CLI, proxies, boring services)",
        ],
      },
    ],
  },
  {
    section: "22. ASP.NET Core",
    tier: "Secondary",
    groups: [
      {
        subsection: "Platform",
        items: [
          "Why ASP.NET Core shows up in enterprise listings",
          "dotnet CLI: new, restore, build, run, test",
          "C# essentials: types, nullable, async/await, LINQ at a reading level",
          "Program.cs, DI container, middleware pipeline",
          "Minimal APIs vs. MVC controllers",
          "appsettings.json and environments",
          "Entity Framework Core vs. Dapper — awareness",
          "Migrations in EF Core",
          "Authentication middleware and [Authorize]",
          "Kestrel, reverse proxy, and IIS as a hosting footnote",
        ],
      },
      {
        subsection: "Enough to Converse",
        items: [
          "NuGet, csproj, and solution files",
          "xUnit / NUnit smoke test",
          "Swagger via Swashbuckle / built-in OpenAPI",
          "When a C# shop is not a Node shop — and that's fine",
        ],
      },
    ],
  },
  {
    section: "7. Professional and Interview Skills",
    tier: null,
    groups: [
      {
        subsection: "Working with Humans",
        items: [
          "Write PRs a reviewer can finish in one sitting",
          "Give and take review without ego",
          "Estimate as a range, then update when you learn",
          "Say 'I don't know; I'll find out by X' out loud",
          "Document the why, not the code restatement",
          "Meeting hygiene: agenda, notes, decisions",
          "Ask for the actual user problem before the requested widget",
          "Leave the codebase better than you found it, in small ways",
        ],
      },
      {
        subsection: "Interviewing",
        items: [
          "A 60-second story of a project you shipped",
          "STAR stories for conflict, failure, and ambiguity",
          "Whiteboard / pair: talk while you think, ask clarifying questions",
          "DSA enough for the jobs you want (arrays, maps, trees, BFS/DFS, two pointers)",
          "System design lite: requirements, data, APIs, bottlenecks, tradeoffs",
          "Read a job spec and map it to this checklist honestly",
          "Questions you ask them: team, on-call, code review, product",
          "Take-home: timebox, README, tests, don't gold-plate",
          "Negotiation: numbers, not vibes; total comp not just salary",
          "A public GitHub that is a portfolio, not a junk drawer",
        ],
      },
    ],
  },
  {
    section: "24. Suggested Practice Projects",
    tier: null,
    groups: [
      {
        subsection: "Project 1: Personal Site",
        items: [
          "Semantic, responsive personal site in HTML/CSS only",
          "A projects page with 3 case-study writeups",
          "Accessible contact form (even if it just mailto:)",
          "Lighthouse 90+ on performance and a11y",
          "Deploy on a static host with a custom domain",
        ],
      },
      {
        subsection: "Project 2: Admin Dashboard",
        items: [
          "Table of records with sort, filter, pagination",
          "Create / edit drawer or page with validated fields",
          "Optimistic toggle for a boolean status",
          "Empty and error states that are not blank screens",
          "Role-flavored UI (viewer vs. editor) even if mocked",
          "Charts from real aggregates (keep them honest)",
          "Keyboard-accessible dialogs and table",
          "Seed data so a reviewer can click around immediately",
        ],
      },
      {
        subsection: "Project 3: REST API",
        items: [
          "CRUD resource with Postgres + Prisma (or equivalent)",
          "Zod validation on every write",
          "Cursor pagination and consistent error bodies",
          "Integration tests on the handlers",
          "OpenAPI document that matches the code",
          "Docker compose: api + db",
        ],
      },
      {
        subsection: "Project 4: Auth-backed App",
        items: [
          "Email/password or social login that is real, not a fake user",
          "Verified session on every mutation",
          "Per-user rows; IDOR test that fails closed",
          "Password reset flow",
          "Logout that actually revokes",
        ],
      },
      {
        subsection: "Project 5: Full-stack Product Slice",
        items: [
          "One user problem, end to end, in production",
          "Next.js (or equivalent) UI + API + Postgres",
          "CI on PR, deploy on main",
          "Error tracking and a health check",
          "A README that a stranger can run",
          "A 3-minute demo script",
        ],
      },
    ],
  },
  {
    section: "8. Job Readiness Criteria",
    tier: null,
    groups: [
      {
        subsection: null,
        items: [
          "Can ship a CRUD feature in the stack without a tutorial open",
          "Can explain every line in a PR you wrote last month",
          "Can find a bug with DevTools and a failing test instead of guessing",
          "Can model a simple domain in Postgres with sane keys and nulls",
          "Can add authz to an endpoint without leaking other users' rows",
          "Can deploy, migrate, and roll back without folklore",
          "Can review a junior PR and leave actionable comments",
          "Have 2–3 projects online with source, live URL, and a writeup",
          "Can talk through a production incident you caused or inherited",
          "Know what you don't know, with a plan for the next skill",
          "Resume matches this checklist — no keyword stuffing you cannot defend",
          "A week of applying and interviewing does not require a new stack",
          "Comfortable pairing for 45 minutes on an unfamiliar file",
          "Written English good enough for tickets, PRs, and docs",
          "Opinionated about tradeoffs, not about brands",
        ],
      },
    ],
  },
];

/** Exact title → Medium, except Monitoring which is section-scoped. */
export const MEDIUM_TITLES = new Set([
  "WebSockets Basics",
  "OpenAPI and Swagger Basics",
  "Background Jobs Basics",
  "Monitoring Basics",
  "CI/CD Basics",
]);

/**
 * @param {string} section
 * @param {string} title
 * @param {Tier} sectionTier
 * @returns {Tier}
 */
export function itemTier(section, title, sectionTier) {
  if (MEDIUM_TITLES.has(title)) return "Medium";
  if (title === "Monitoring" && section.startsWith("18.")) return "Medium";
  return sectionTier;
}
